In [1]:
import kcounter as kc
from sklearn.feature_extraction import DictVectorizer
import pandas as pd
from collections import defaultdict as dd
import sys
import numpy as np
# import matplotlib.pyplot as plt
import json

/home/itsalkovsky/miniconda3/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.25.0
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
clusters_df = pd.read_csv('mmseqs_REPEAT_REGIONS_1_cluster_FILTERED.tsv', sep = '\t', names=['0','1'])
sequences = open('Alongiglumis_CN58138_pseudomolecules.v1.fasta.pass.list.REPEAT_REGIONS.gff3.fas')
seq_dict = {}
n = 0
for line in sequences.readlines():
    n+=1
    if n%10000==0:
        print(n)
    if '>' in line:
        name = line.strip()[1:]
    else:
        seq = line.strip()
        seq_dict[name]=seq
sequences.close()

len_df = 0
file = open('out_treetable_v6.txt')
for line in file.readlines():
    if len(line.strip().split('\t')) > len_df:
        len_df = len(line.strip().split('\t'))
last_column = len_df
file.close()
df = pd.read_csv('out_treetable_v6.txt', sep = '\t', names = [i for i in range(0,last_column)])
df = df.fillna(0)
df['cluster_full_name'] = df[df.columns[0:2]].apply(
    lambda x: ':'.join(x.dropna().astype(str)),
    axis=1)
all_clusters_names = (df['cluster_full_name'].tolist())
df = df.drop(columns=['cluster_full_name'])
rev_cols = list(df.columns)
print('rev_cols',rev_cols)
rev_cols.reverse()
for col in rev_cols:
    if len(set(df[col].values)) == 1:
        diff_column = int(col)+1
        # print('diff_column',diff_column)
        break

10000
20000
30000
40000
50000
60000
70000
80000
90000
rev_cols [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]


In [18]:
def make_groups(df, column): #создает словарь, где ключ - клада, значение - список строк, которые в нее входят 
    grps = {}
    for i, row in df.iterrows():
        if row[column] not in grps:
            grps[row[column]] = []
        grps[row[column]].append(i)
    return(grps)

def make_tree(df,groups, column, last_col=last_column):
    node = {}
    for k, v in groups.items():
        for col in (range(column, last_col)): # recording the name of specific clade in which we look for kmers
            if (df.iloc[v,col].unique()[0]) == 0:
                needed_column=col
                break
            elif col==last_col-1:
                needed_column=col
                break
            elif len(df.iloc[v,col].unique()) == 1:
                continue
            else:
                needed_column = col
                break
        subgroups = make_groups(df.iloc[v], needed_column)
        if len(subgroups) == 1 or int(column) == last_col:
            for key, v in subgroups.items(): #k is taken from previous group index
                node[k] = v
        else:
            add_node = make_tree(df, subgroups, column + 1)
            node[k] = add_node
    return(node)

def get_leaves(branch):
    global leaves
    if type(branch) is list:
        leaves.extend(branch)
    else:
        for k, v in branch.items():
            get_leaves(v)

def make_matrix(group_item):
    max_kmer = 0
    rows = group_item[1]
    clade_name = group_item[0]
    print(df.shape[0], len(rows))
    # o=input()
    df_temp = df.iloc[rows]
    # return(df_temp)
    df_temp['cluster_full_name'] = df_temp[df_temp.columns[0:2]].apply(
    lambda x: ':'.join(x.dropna().astype(str)),
    axis=1)
    clusters_names = (df_temp['cluster_full_name'].tolist())
    # print('103\n',clusters_names)
    cluster_temp = clusters_df[clusters_df.iloc[:,0].isin(clusters_names)]
    cluster_temp_listed = cluster_temp.groupby('0')['1'].apply(list).reset_index(name='1')
    cluster_seq_dict = {}
    print('cluster_temp', cluster_temp.shape[0])
    print('cluster_temp_listed', cluster_temp_listed.shape[0])
    clusters_sizes = {}
    for i, row in cluster_temp_listed.iterrows():
        clusters_sizes[row[0]] = len(row[1])
        cluster_seq_dict[row[0]] = row[1]
    all_dicts = []
    cluster_names = []
    n = 0
    len_clusters = len(cluster_seq_dict)
    print('cluster_seq_dict len', len(cluster_seq_dict))
    # print('len cluster_names', len(cluster_names))
    for cl in clusters_names: # поменять словарь откуда кластеры брать на тот, который соответствует порядку кластеров в таблице
        cluster_kmers_amount_dict = dd(int)
        seqs_in_cluster_list = []
        n+=1
        if n%500==0:
            print(f'{n} of {len_clusters}')
        cluster_names.append(cl)
        for i in cluster_seq_dict[cl]:
            seqs_in_cluster_list.append(seq_dict[i])
        for seqq in seqs_in_cluster_list:
            kmers = kc.count_kmers(seqq, 13, canonical_kmers=True)
            for key in kmers.keys():
                cluster_kmers_amount_dict[key]+=1
        all_dicts.append(cluster_kmers_amount_dict)

    dictvectorizer = DictVectorizer(sparse=False, dtype=np.int16)
    features = dictvectorizer.fit_transform(all_dicts)
    feature_name=dictvectorizer.get_feature_names_out()
    print('first amount of kmers ',len(feature_name))

    sum_arr = np.sum(features, axis=0)
    sum_list = sum_arr.tolist()
    columns_to_del = np.where(sum_arr < 4)[0]
    features = np.delete(features, columns_to_del, axis=1)

    feature_name = np.delete(feature_name, columns_to_del)
    sum_arr = np.delete(sum_arr, columns_to_del)
    print(features)
    print('kmers after filtering ', len(feature_name))
    return(features, feature_name, clusters_names, sum_arr, clusters_sizes)

def make_csv(candidate_kmers, specificity_arr, sensitivity_arr, absolute_counts, cluster_name):
    quality_arr = specificity_arr*sensitivity_arr
    df_out = pd.DataFrame({'kmer':candidate_kmers, 'specificity':specificity_arr, 'sensitivity':sensitivity_arr,
                           'quality':quality_arr, 'absolute_counts':absolute_counts})
    df_out.to_csv(f'./out_csv/{cluster_name}.csv', index=False)

def greedy_selection_recursive(sorted_temp_matrix, clusters_names, clusters_sizes, leaves,
                     sorted_candidate_kmers, local_kmers_of_choice=[], prev_covered_clusters=[],
                     depth=1):
    kmer_occur = -1
    thresh = 0.6
    kmer_of_choice = None
    max_coverage = 0
    max_covered_clusters = []
    for i in sorted_candidate_kmers:
        # print('NEXT KMER' , i)
        coverage = 0
        covered_clusters = []
        kmer_occur+=1
        if i in local_kmers_of_choice:
            continue
        cluster_occur = -1
        for cluster in leaves:
            cluster_occur+=1
            if cluster in prev_covered_clusters:
                continue
            if sorted_temp_matrix[cluster_occur][kmer_occur]/clusters_sizes[clusters_names[cluster]] >= thresh:
                coverage+=1
                covered_clusters.append(cluster)
                # print('CLUSTER APPENDED', cluster, covered_clusters)
        if coverage > max_coverage:
            max_coverage = coverage
            kmer_of_choice = i
            max_covered_clusters = covered_clusters
    print('total covered clusters', max_covered_clusters)
    local_kmers_of_choice.append(kmer_of_choice)
    # print('all covered clusters ', prev_covered_clusters)
    prev_covered_clusters.extend(max_covered_clusters)
    print('prev ', len(prev_covered_clusters))
    print('chosen kmers ', len(local_kmers_of_choice))
    print('last kmer ', kmer_of_choice)
    # o = input()
    if len(prev_covered_clusters)==len(leaves) or depth == 40: # возможно +max_coverage тут лишний
        print('DEPTH 40')
        print(prev_covered_clusters)
        prev_covered_clusters.extend(max_covered_clusters)
        print('max covered clusters', max_covered_clusters)
        print('local kmers of choice', local_kmers_of_choice)
        print('prev_covered_clusters', prev_covered_clusters, len(local_kmers_of_choice))
        return (max_covered_clusters, local_kmers_of_choice)
    depth+=1
    print('depth ',depth)
    prev_covered_clusters, local_kmers_of_choice = greedy_selection(sorted_temp_matrix, clusters_names, clusters_sizes, leaves,
                                                                    sorted_candidate_kmers, local_kmers_of_choice,
                                                                    prev_covered_clusters, depth) 
    
def greedy_selection(sorted_temp_matrix, clusters_names, clusters_sizes, leaves, sorted_candidate_kmers):
    iterations = 1
    kmer_coverage_layers = {}
    clusters_coverage_layers = {}
    global_kmers_of_choice = []
    while iterations<5:
        print('global_kmers_of_choice', global_kmers_of_choice)
        thresh = 0.6
        kmer_of_choice = None
        local_kmers_of_choice = []
        layer_covered_clusters = []
        depth = 1
        print('sorted kmers', len(sorted_candidate_kmers))
        while depth<40:
            max_covered_clusters = []
            max_coverage = 0
            kmer_occur = -1
            for i in sorted_candidate_kmers:
                coverage = 0
                covered_clusters = []
                kmer_occur+=1
                if i in local_kmers_of_choice or i in global_kmers_of_choice:
                    continue
                cluster_occur = -1
                for cluster in leaves:
                    cluster_occur+=1
                    if cluster in layer_covered_clusters:
                        continue
                    if sorted_temp_matrix[cluster_occur][kmer_occur]/clusters_sizes[clusters_names[cluster]] >= thresh:
                        coverage+=1
                        covered_clusters.append(cluster)
                if coverage > max_coverage:
                    max_coverage = coverage
                    kmer_of_choice = i
                    max_covered_clusters = covered_clusters
            print('max covered clusters', max_covered_clusters)
            local_kmers_of_choice.append(kmer_of_choice)
            # print('all covered clusters ', prev_covered_clusters)
            layer_covered_clusters.extend(max_covered_clusters)
            print('prev_covered clusters', layer_covered_clusters)
            if len(layer_covered_clusters)>=len(leaves) or not max_covered_clusters:
                kmer_coverage_layers[f'layer_{iterations}'] = local_kmers_of_choice
                clusters_coverage_layers[f'layer_{iterations}'] = layer_covered_clusters
                global_kmers_of_choice.extend(local_kmers_of_choice)
                depth = 40
                continue
            # o = input()
            # if len(prev_covered_clusters)==len(leaves) or depth == 40: # возможно +max_coverage тут лишний
            #     print('DEPTH 40')
            #     print(prev_covered_clusters)
            #     prev_covered_clusters.extend(max_covered_clusters)
                # return (max_covered_clusters, local_kmers_of_choice)
            depth+=1
            print('depth ',depth)
        kmer_coverage_layers[f'layer_{iterations}'] = local_kmers_of_choice
        clusters_coverage_layers[f'layer_{iterations}'] = layer_covered_clusters
        global_kmers_of_choice.extend(local_kmers_of_choice)
        iterations+=1
    return(kmer_coverage_layers, clusters_coverage_layers, thresh)
    

def count_uniq(tree, matrix, feature_name, clusters_names, sum_arr, clusters_sizes):
    global leaves
    f = open('greedy_selection.tsv', 'w')
    f.write('clade\tlayer\tkmers\tclusters\tlen_kmers\tlen_clusters\tspecificity_range\tin_cluster_sensitivity_threshold\n')
    for k,v in tree.items():
        print('k', k)
        leaves = []
        get_leaves(v)
        print('len leaves', len(leaves))
        temp_matrix = matrix[leaves]
        clade_sum_arr = np.sum(temp_matrix, axis=0)
        current_clade_size = sum([clusters_sizes[clusters_names[i]] for i in leaves])
        print('leaves', leaves)
        columns_to_del = np.where(clade_sum_arr < int(0.3*current_clade_size))[0] # фильтрация N% топовых по чувствительности кмеров
        print('размер клады и threshold',current_clade_size, int(0.3*current_clade_size))
        # удаляем новые отфильтрованные столбцы
        clade_sum_arr = np.delete(clade_sum_arr, columns_to_del)
        temp_sum_arr = np.delete(sum_arr, columns_to_del)
        temp_matrix = np.delete(temp_matrix, columns_to_del, axis=1)
        temp_feature_name = np.delete(feature_name, columns_to_del)

        division_sign = clade_sum_arr/temp_sum_arr # сумма каждого кмера в кладе делится на сумму кмера во всей матрице,получается список специфичностей
        div_sign_desc = np.argsort(-division_sign)[:] # фильтрация первых N по специфичности кмеров 

        # print(div_sign_desc)
        candidate_kmers = (temp_feature_name[div_sign_desc.tolist()])
        # print(candidate_kmers)
        specificity_arr = (division_sign[div_sign_desc.tolist()])
        high_spec_end = 1
        low_spec_end = 0.9
        specificity_arr_index_low = np.where(specificity_arr>low_spec_end)[0]
        specificity_arr_index_high = np.where(high_spec_end>specificity_arr)[0]
        specificity_arr_index = list(set(specificity_arr_index_high) & set(specificity_arr_index_low))
        specificity_arr = specificity_arr[specificity_arr_index]
        candidate_kmers = candidate_kmers[specificity_arr_index]
        print((specificity_arr_index))
        # print(specificity_arr[67240:67250])
        # out = ''
        # for i, v in enumerate(specificity_arr):
        #     if v == 1:
        #         out+=f'{candidate_kmers[i]}\n'

        # f = open('specificity100kmers.txt', 'w')
        # f.write(out)
        # f.close()
        # print(specificity_arr) # отбор значений чувствительности топовых по чувствительности кмеров
        # o = input()
        sensitivity_arr = (clade_sum_arr[div_sign_desc.tolist()]/current_clade_size)[specificity_arr_index]
        # print(sensitivity_arr)
        absolute_counts = (temp_sum_arr[div_sign_desc.tolist()])[specificity_arr_index]
        # print(absolute_counts) # абсолютные значения суммы данных кмеров во всем датасете
        local_counts = (clade_sum_arr[div_sign_desc.tolist()])
        sorted_temp_matrix = temp_matrix[:, div_sign_desc.tolist()][:, specificity_arr_index]
        print(temp_matrix.shape)
        print(sorted_temp_matrix.shape)
        candidate_kmers_sens_sort_order = np.argsort(-sensitivity_arr)
        sorted_candidate_kmers = (candidate_kmers[candidate_kmers_sens_sort_order])
        sorted_temp_matrix = sorted_temp_matrix[:, candidate_kmers_sens_sort_order.tolist()]
        make_csv(candidate_kmers, specificity_arr, sensitivity_arr, absolute_counts, k)
        # local_kmers_of_choice = []
        # iterations = 0
        # while iterations < 5:
        #     prev_covered_clusters, local_kmers_of_choice = greedy_selection(sorted_temp_matrix, clusters_names, clusters_sizes, leaves,
        #                                                                     sorted_candidate_kmers, local_kmers_of_choice, prev_covered_clusters=[])
        #     iterations+=1
        #     print('iteration ', iterations)

        kmer_coverage_layers, clusters_coverage_layers, threshold = greedy_selection(sorted_temp_matrix, clusters_names, clusters_sizes, leaves, sorted_candidate_kmers)
        print(kmer_coverage_layers)
        print(clusters_coverage_layers)
        for i in kmer_coverage_layers.keys():
            f.write(f'{k}\t{i}\t{",".join(kmer_coverage_layers[i])}\t'
                    f'{",".join(list(map(str,clusters_coverage_layers[i])))}\t{len(kmer_coverage_layers[i])}\t'
                    f'{len(clusters_coverage_layers[i])}\t{high_spec_end}-{low_spec_end}\t{threshold}\n')
        # break


In [4]:
grp = make_groups(df, diff_column-1)

In [5]:
tree = make_tree(df, grp, diff_column)
tree = tree[list(tree.keys())[0]]

In [6]:
for it in grp.items():
    i = it
    print(i)

('Copia', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219,

In [8]:
print(i)

('Copia', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219,

In [7]:
features, feature_name, clusters_names, sum_arr, clusters_sizes =  make_matrix(i)

2101 2101
cluster_temp 14155
cluster_temp_listed 2101
cluster_seq_dict len 2101
500 of 2101
1000 of 2101
1500 of 2101
2000 of 2101
first amount of kmers  6581449
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
kmers after filtering  1402690


In [19]:
leaves = []
count_uniq(tree, features, feature_name, clusters_names, sum_arr, clusters_sizes)

k Ale
len leaves 238
leaves [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 2